TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# In a Diamond Support Module, install
# templates like this
#
DB += EL2624.template
DB += EL1004.template
DB += EL1014.template
DB += EK1101.template
DB += EL2004.template
DB += EL3702.template
DB += EL3104.template
DB += EL3201.template
DB += EL3202-0010.template
DB += EL3314.template
DB += NI9144-rev4.template
DB += NI9144.template
DB += EL3602.template
DB += MASTER.template
DB += gadc.template
DB += gadc-periodic.template
DB += xfc.template
DB += EL3162.template
DB += EK1100.template
DB += EK1122.template
DB += EL3602.template
DB += EL4134.template
DB += EL4732.template
DB += EL1124.template
DB += EL1502.template
DB += EL2024-0010.template
DB += EL2124.template
DB += EL9410.template
DB += EL9512.template
DB += EL9505.template
DB += EP3174-0002.template
DB += EP3204-0002.template
DB += EP3314-0002.template
DB += EP4174-0002.template
DB += EP4374-0002.template
DB += EP2338-0002.template
DB += EP2624-0002.template
DB += EP1122-0001.template

#----------------------------------------------------
# In a Diamond IOC Application, build db files from
# template files like this
#
#DB += BL06I-MO-IOC-01.db
#DB += BL06I-MO-IOC-01_sim.db

#USES_TEMPLATE += $(MOTOR)/db/motor.template
#USES_TEMPLATE += $(MOTOR)/db/basic_motor.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
